### ISSUE TITLE
TA feedback hw02

### ISSUE THREAD

**Issue by aleurcelay** [STAT545-UBC-hw-2019-20/stat545-hw-dy-lin#5]
Hi @dy-lin :),
here are a few comments about your assignment:

- Great job using GitHub preview 💯 
- You may want to fix your tables as the columns are way too clase which makes them hard to read (HTML preview). There is also an issue when you use `datable()` as tables are not rendering
- Ok you are assuming life expectancy goes from 0 to 83 which is incorrect. You should've looked into the summary of the dataset or used `min()` as well
- You could've added `geom_density()` to your histogram to see the distribution
- The scatter plot from exercise 3 is too messy. Subsetting is always a good idea. Also try to make plots that a specific purpose!
- The second plot is very useful! 👍 
- Good job with the extra exercises!

**Comment by dy-lin** [comment]
Hi @aleurcelay,
For the 0 to 83, I tried to make it clear that those are the potential/reasonable values for life expectancy in general (choosing 83 as the max, but that 0 is also a reasonable value that could happen). I reiterated that the actual min and max later in the assignment using `min()` and `max()`.

The GitHub HTML preview was very handy before learning about the use of GitHub Pages! (for some reason I guess DataTables don't render well using that the HTML preview, but I didn't really know how else to do it). I have gone back and made GitHub Pages for my past assignments as to be consistent with hw03.
